services:
  mongodb:
    image: mongo:latest
    container_name: mangavault-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS:-password}
      - MONGO_INITDB_DATABASE=mangavault
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - mangavault-net
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mangavault-api:
    build: 
      context: .
    container_name: mangavault-app
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      # REFACTOR: Formato lista para evitar errores de sintaxis YAML
      - SPRING_DATA_MONGODB_URI=mongodb://${MONGO_USER:-admin}:${MONGO_PASS:-password}@db:27017/mangavault?authSource=admin
      - APP_EXTERNAL_API_JIKAN_BASE_URL=https://api.jikan.moe/v4
      - LOG_LEVEL_APP=TRACE
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_MONGODB_CORE_MONGOTEMPLATE=DEBUG
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=DEBUG
      - SPRING_DOCKER_COMPOSE_ENABLED=false
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - mangavault-net
    deploy:
      resources:
        limits:
          memory: 1G

  mongo-express:
    image: mongo-express
    container_name: mangavault-gui
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER:-admin}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASS:-password}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_USER:-admin}:${MONGO_PASS:-password}@mongodb:27017/
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - mangavault-net

networks:
  mangavault-net:
    driver: bridge

volumes:
  mongodb_data: