spring.application.name=MangaVault-API

# --- OBSERVABILIDAD (ACTUATOR) ---
# Exponer todos los endpoints de monitoreo (Salud, Métricas, Env, etc)
management.endpoints.web.exposure.include=health,info,metrics,prometheus,liveness,readiness

# Mostrar detalles de salud (útil para saber si MongoDB está caído)
management.endpoint.health.show-details=always

# --- LOGGING (ESTRUCTURADO) ---
# En 2026 usamos logs con IDs de trazabilidad para buscar errores fácil
logging.pattern.level=%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]
logging.level.com.mangavault=DEBUG

# Solo reinicia si cambian archivos en estas rutas
spring.devtools.restart.additional-paths=src/main/java
# Excluye recursos estáticos que no necesitan reinicio de contexto
spring.devtools.restart.exclude=static/**,public/**

# --- CONFIGURACIÓN DE APIs EXTERNAS ---
app.external-api.jikan.base-url=https://api.jikan.moe/v4

logging.level.org.springframework.security=DEBUG